name: CI
on: [push]
jobs:
  build:
    name: Build on Node ${{ matrix.node }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["22.x", "20.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Build
        run: pnpm build
